/*
 * EXTI_CONFIG.h
 *
 *  Created on: May 21, 2023
 *      Author: ihesh
 */

#ifndef EXTI_CONFIG_H_
#define EXTI_CONFIG_H_


#define EXTI_LINE0_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE1_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE2_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE3_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE4_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE5_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE6_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE7_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE8_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE9_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE10_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE11_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE12_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE13_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE14_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE15_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE16_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE17_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE18_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE19_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE20_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE21_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE22_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE23_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE24_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE25_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE26_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE27_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE28_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE29_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE30_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE31_ENABEL 		MEXTI_DISABLE




#define EXTI_LINE0_SENSE_MODE		MEXTI_DISABLE



#endif /* EXTI_CONFIG_H_ */
